pipeline {
    agent any


    environment {
        AWS_REGION = 'ap-south-1'
    }

    stages {
        stage('Deploy EC2') {
            steps {
                withFolderProperties {
                    withAWS(credentials: 'AWS', region: AWS_REGION ) {
                        cfnUpdate(
                            stack: "${env.environment}-jumphost",
                            file: 'iac/aws/cloudformation/ec2/jumphost.yml',
                            params: [
                                environment: env.environment,
                                keyName:env.keyName                            
                            ],
                            timeoutInMinutes: 30
                        )
                    }
                }
            }
        }   
        stage('Deploy RDS-Cluster') {
            steps {
                withFolderProperties {
                    withAWS(credentials: 'AWS', region: AWS_REGION) {
                        cfnUpdate(
                            stack: "${env.environment}-Cluster",
                            file: 'iac/aws/cloudformation/rds/rds.yml',
                            params: [
                                environment: env.environment,
                                dbUsername: env.dbUsername,
                                engine: env.engine,
                                engineVersion: env.engineVersion

                            ],
                            timeoutInMinutes: 30
                        )
                    }
                }
            }
        }
    }
}
