# Use the official WordPress image as the base
FROM wordpress:apache

# Expose the default WordPress port
EXPOSE 80

# Set the default command to run the WordPress container
CMD ["apache2-foreground"]
